def write_header(outfile, title, author):
    outfile.write(r"""
\documentclass[12pt,a4paper]{book}
\usepackage[noenc]{tipa}
\usepackage[utf8x]{inputenc}
\usepackage{lmodern,textcomp}
%\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{url}
\usepackage[english]{babel}

\usepackage{tipx}
\usepackage[geometry,weather,misc,clock]{ifsym}
\usepackage{pifont}
\usepackage{eurosym}
\usepackage{subcaption}
\usepackage[section]{placeins}
\usepackage{ulem}
\usepackage{a4wide}
\usepackage[dvipsnames,svgnames]{xcolor}
\usepackage[pdftex]{graphicx}

\usepackage[paperwidth=8.125in,paperheight=10.25in]{geometry}


\usepackage{hyperref}
\usepackage{titlesec}
\titleclass{\part}{top}
\titleformat{\part}[display]
  {\normalfont\huge\bfseries}{\centering\partname\ \thepart}{20pt}{\Huge\centering}
\titlespacing*{\part}{0pt}{50pt}{40pt}
% commands generated by html2latex

% Page layout (geometry)
%\setlength\voffset{-1in}
%\setlength\hoffset{-1in}
%\setlength\topmargin{2.54cm}
%\setlength\oddsidemargin{2.54cm}
%\setlength\textheight{22.86cm}
%\setlength\textwidth{16.509998cm}
%\setlength\footskip{0.0cm}
%\setlength\headheight{0cm}
%\setlength\headsep{0cm}

\let\oldcenter\center
\let\oldendcenter\endcenter
\renewenvironment{center}{\setlength\topsep{0pt}\oldcenter}{\oldendcenter}

\title{""")
    outfile.write(title)
    outfile.write(r"""}
\author{""")
    outfile.write(author)
    outfile.write(r"""}
\date{}
\begin{document}
\maketitle
""")

def write_footer(outfile):
    outfile.write(r"""
\end{document}""")

def write_image(outfile, image_file):

    outfile.write(r"""
\begin{figure*}[h!]
    \centering
    \begin{subfigure}[t]{1.00\textwidth}
        \includegraphics[width=\linewidth]{""")
    outfile.write(image_file)
    outfile.write(r"""}
    \end{subfigure}
    %\caption*{}
\end{figure*}
""")